/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
    id("org.jetbrains.kotlin.jvm") version "1.5.20"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    testImplementation ("io.cucumber:cucumber-java:6.10.4")
    testImplementation ("io.cucumber:cucumber-junit:6.10.4")
    testImplementation ("junit:junit:4.13.2")
    implementation ("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}

group = "apitestcucumber"
version = "1.0.0-SNAPSHOT"
description = "apitestcucumber"
java.sourceCompatibility = JavaVersion.VERSION_1_8

configurations {
    cucumberRuntime {
        extendsFrom testImplementation
    }
}

task cucumber() {
    dependsOn assemble, testClasses
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = ["--plugin", "pretty", "--glue", "apitestcucumber", "src/test/resources"]
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}